### ISSUE TITLE
A few suggestions if you have time!

### ISSUE THREAD

**Issue by ctralie** [bmershon/shape-google#1]
*I really like how you were rendering the EGI.  in addition to changing the colors, you can also change the geometry.  So make the radius of a point on the sphere you're saving proportional to the counts in that bin.  Also, it looks like the spheres are pretty low resolution, and the colors don't have very much contrast between red and blue.  Actually, I think switching to higher resolution will fix this

*Nice analysis with the self-similarity images.  That's exactly what I wanted you to look for there

*I wouldn't expect the 1D earth mover's to work on any of the 2D histograms.  I'm a bit surprised it doesn't improve the D2, though.  It might improve it if you use more bins in the D2.  Try it also on the basic shell descriptor

**Comment by bmershon** [comment]
_And here I thought I had escaped the assignment to move onto the next one!_

I definitely enjoyed looking at the self-similarity images the most. Staring at precision recalls, however, has got me down...

I'll try these things out tomorrow. I was starting to get bogged down after spending all day yesterday and today diagnosing the cause of subtle changes in my graphs. I would like to take a step back and discuss (probably after this is all done) *why* at a high level the descriptors should or shouldn't work well with various combinations of comparators. 

There's some big picture stuff that my empirical tests have not yet illuminated for me. For one thing, it would be nice if my self-similarity matrices could tell me why D2 and A3 may or may not be categorically different. Perhaps my binning is throwing me off, but I thought using your provided defaults would work well enough.

Two cool things:

Hopefully my attempt to be *fancy* in calculating EMD-1D line is correct:
```py
def compareHistsEMD1D(H):
    K = H.shape[0]
    N = H.shape[1]
    D = np.zeros((N, N))
    CDF = np.zeros((K, N))
    CDF[0, :] = H[0, :]
    for i in range(1, K):
        CDF[i, :] = CDF[i - 1, :] + H[i, :]
    # Use transposes and broadcasting so that third dimension can be used to sum
    # corresponding distances.
    D = np.sum(np.absolute(CDF[:, np.newaxis, :].T - CDF.T[np.newaxis, :, :]), axis=2)
    return D
```

And hopefully I didn't throw things off when I used shuffling and permutation matrices instead of rejection sampling:

```py
# Fisher-Yates linear in-place shuffle (so fancy)
def shuffle(array):
    m = len(array) - 1
    # while there are elements to shuffle
    while m > 0:
        # pick a random element from the end
        i = np.random.randint(m, size=1)[0]
        t = array[i]
        array[i] = array[m]
        array[m] = t
        m = m - 1
```

**Comment by ctralie** [comment]
Fancy!  Yeah don't worry about this too much if you don't have time.  I was just giving you more things to play around with, but the only thing I care about for grading is a plot showing shells with EMD.  I have played similar tricks with going to 3D matrices so that's an awesome idea, though I'd have to scratch my head for a bit to see if it was right.  For Fisher Yates, that is very cool, though you could do it with np.random.permutation also.

**Comment by bmershon** [comment]
Updated with Shells: https://github.com/bmershon/shape-google/blob/master/README.md#changing-parameters

I'll repackage and upload to Sakai again.

**Comment by ctralie** [comment]
Yeah no worries, great work otherwise!  Since you always want to do extra, I was just giving you some stuff you could play around with in the future.  But there's enough work left in the course to keep you busy in the mean time :)
